### ISSUE TITLE
datacube lacks pytest plugin packages for application built on odc integration testing

### ISSUE THREAD

**Issue by pindge** [opendatacube/datacube-core#1274] opened 2022-06-08 06:31 UTC
`digitalearthau` (https://github.com/GeoscienceAustralia/digitalearthau) github repo has a testing package that prepares an empty database for odc testing, `digitalearthau` split pathways with current `datacube-core` years ago, it originally was kept to enable testing exclusively `digitalearthaustralia` products, most of the repo's code are no longer maintained, but this testing package would be great assets to include in `opendatacube/datacube-core`

https://github.com/GeoscienceAustralia/digitalearthau/blob/071d3e649b2c074a660220bc03857af623d7855b/digitalearthau/testing/factories.py#L38-L61

https://github.com/GeoscienceAustralia/digitalearthau/blob/071d3e649b2c074a660220bc03857af623d7855b/digitalearthau/testing/factories.py#L64-L74

https://github.com/GeoscienceAustralia/digitalearthau/blob/071d3e649b2c074a660220bc03857af623d7855b/digitalearthau/testing/factories.py#L77-L100

this allows applications built on odc to `init` database, `add metadata`, `add product` and `add datasets` for integration testing, i.e.

https://github.com/opendatacube/datacube-explorer/blob/e8c1c268e4b4c9bb4d75ab9968a25e1b539f5761/integration_tests/conftest.py#L42-L106

**Comment by omad** [comment] 2022-11-21 05:41
See Also https://github.com/opendatacube/datacube-explorer/issues/472 and https://github.com/opendatacube/datacube-explorer/pull/490 and https://github.com/opendatacube/odc-tools/pull/524

**Comment by omad** [comment] 2022-11-21 05:41
See Also https://github.com/opendatacube/datacube-explorer/issues/472 and https://github.com/opendatacube/datacube-explorer/pull/490 and https://github.com/opendatacube/odc-tools/pull/524

**Comment by Ariana-B** [comment] 2023-05-23 01:52
Duplicate of #1334

**Closed as completed by Ariana-B** 2023-05-23 01:52 UTC
Labels: enhancement
