### ISSUE TITLE
Add a query of spatial and/or temporal bounds for a product

### ISSUE THREAD

**Issue by GypsyBojangles** [opendatacube/datacube-core#186] opened 2017-03-08 01:53 UTC
For some grid based workflows, it is useful to know the bounding box for a query, to then work out what cells are inside that grid. There is currently no function that can use the database index for each dimension to work out the bounds. Getting the time range is also useful for previewing what data is available e.g. for the dashboard.

**Comment by benjimin** [comment] 2017-03-14 22:39
It sounds like a sensible feature. With the current database it should be reasonably trivial to get a bounding box (padded and in the index CRS), but comparatively expensive to get a tight polygon envelope.

An alternative approach is to use GridWorkflow (to convert a query to tiles without needing to know the cell indices beforehand), potentially chunking by time-window manually if you can't handle all the results at once.

**Comment by omad** [comment] 2017-10-05 03:47
Where are you up to with your test code for this @andrewdhicks?

**Comment by omad** [comment] 2018-02-26 03:00
I've created Issue #366 that is in some ways a duplicate of this one, but, since it's coming at the problem from a different angle, I'm going to close this one and point everyone there.

**Closed as completed by omad** 2018-02-26 03:00 UTC
Labels: improvement proposal
