### ISSUE TITLE
New ingested datasets are not able to load while reprojecting under rasterio

### ISSUE THREAD

**Issue by Bis-Bala** [opendatacube/datacube-core#242] opened 2017-06-05 00:02 UTC
### Background
I am creating geobox out of my polygon with resolution and using gridworkflow to load datasets. This has been fine till on last Friday and since then it was failing. 
### Expected behaviour
I have been able to get dataset using reprojected  geobox.

### Actual behaviour
rasterio is giving following error CPLE_IllegalArgError.
ERROR:rasterio._gdal:CPLE_IllegalArg in Temporary destination dataset for _reproject(): GDALDataset::GetRasterBand(9) - Illegal band #

ERROR:rasterio._gdal:CPLE_IllegalArg in panDstBands[0] = 9 ... out of range for dataset.
ERROR:datacube.storage.storage:Error opening source dataset: NetCDF:/g/data/rs0/datacube/002/LS8_OLI_NBAR/20_-26/LS8_OLI_NBAR_3577_20_-26_2013_v1496416918.nc:coastal_aerosol
---------------------------------------------------------------------------
CPLE_IllegalArgError                      Traceback (most recent call last)
<ipython-input-64-0fa68a8587ae> in <module>()
----> 1 ds_new=GridWorkflow.load(tl_ob)

/g/data/v10/public/modules/agdc-py3/1.3.2/lib/python3.6/site-packages/datacube/api/grid_workflow.py in load(tile, measurements, dask_chunks, fuse_func, resampling, skip_broken_datasets)
    349 
    350         dataset = Datacube.load_data(tile.sources, tile.geobox, measurements.values(), dask_chunks=dask_chunks,
--> 351                                      fuse_func=fuse_func, skip_broken_datasets=skip_broken_datasets)
    352 
    353         return dataset

/g/data/v10/public/modules/agdc-py3/1.3.2/lib/python3.6/site-packages/datacube/api/core.py in load_data(sources, geobox, measurements, fuse_func, dask_chunks, skip_broken_datasets)
    489 
    490         return Datacube.create_storage(OrderedDict((dim, sources.coords[dim]) for dim in sources.dims),
--> 491                                        geobox, measurements, data_func)
    492 
    493     @staticmethod

/g/data/v10/public/modules/agdc-py3/1.3.2/lib/python3.6/site-packages/datacube/api/core.py in create_storage(coords, geobox, measurements, data_func)
    426 
    427         for measurement in measurements:
--> 428             data = data_func(measurement)
    429 
    430             attrs = {

/g/data/v10/public/modules/agdc-py3/1.3.2/lib/python3.6/site-packages/datacube/api/core.py in data_func(measurement)
    482                 for index, datasets in numpy.ndenumerate(sources.values):
    483                     _fuse_measurement(data[index], datasets, geobox, measurement, fuse_func=fuse_func,
--> 484                                       skip_broken_datasets=skip_broken_datasets)
    485                 return data
    486         else:

/g/data/v10/public/modules/agdc-py3/1.3.2/lib/python3.6/site-packages/datacube/api/core.py in _fuse_measurement(dest, datasets, geobox, measurement, skip_broken_datasets, fuse_func)
    548                        resampling=measurement.get('resampling_method', 'nearest'),
    549                        fuse_func=fuse_func,
--> 550                        skip_broken_datasets=skip_broken_datasets)
    551 
    552 

/g/data/v10/public/modules/agdc-py3/1.3.2/lib/python3.6/site-packages/datacube/storage/storage.py in reproject_and_fuse(sources, destination, dst_transform, dst_projection, dst_nodata, resampling, fuse_func, skip_broken_datasets)
    204         for source in sources:
    205             with ignore_exceptions_if(skip_broken_datasets):
--> 206                 read_from_source(source, buffer_, dst_transform, dst_nodata, dst_projection, resampling)
    207                 fuse_func(destination, buffer_)
    208 

/g/data/v10/public/modules/agdc-py3/1.3.2/lib/python3.6/site-packages/datacube/storage/storage.py in read_from_source(source, dest, dst_transform, dst_nodata, dst_projection, resampling)
    153                           dst_nodata=dst_nodata,
    154                           resampling=resampling,
--> 155                           NUM_THREADS=OPTIONS['reproject_threads'])
    156 
    157 

/g/data/v10/public/modules/agdc-py3/1.3.2/lib/python3.6/site-packages/datacube/storage/storage.py in reproject(self, dest, dst_transform, dst_crs, dst_nodata, resampling, **kwargs)
    245                                        dst_nodata=dst_nodata,
    246                                        resampling=resampling,
--> 247                                        **kwargs)
    248 
    249 

/g/data/v10/public/modules/agdc-py3-env/20170427/envs/agdc/lib/python3.6/site-packages/rasterio/env.py in wrapper(*args, **kwds)
    268         def wrapper(*args, **kwds):
    269             with Env():
--> 270                 return f(*args, **kwds)
    271         return wrapper

/g/data/v10/public/modules/agdc-py3-env/20170427/envs/agdc/lib/python3.6/site-packages/rasterio/warp.py in reproject(source, destination, src_transform, gcps, src_crs, src_nodata, dst_transform, dst_crs, dst_nodata, resampling, init_dest_nodata, **kwargs)
    268     _reproject(source, destination, src_transform, gcps, src_crs, src_nodata,
    269                dst_transform, dst_crs, dst_nodata, resampling,
--> 270                init_dest_nodata, **kwargs)
    271 
    272 

rasterio/_warp.pyx in rasterio._warp._reproject (rasterio/_warp.cpp:7877)()

rasterio/_err.pyx in rasterio._err.exc_wrap_int (rasterio/_err.c:2098)()

CPLE_IllegalArgError: panDstBands[0] = 9 ... out of range for dataset.

### Steps to reproduce the behaviour

import fiona
from datacube.api import make_mask, GridWorkflow, Tile
from datacube.api.query import query_group_by
from datacube.utils.geometry import CRS, GeoBox, Geometry
from datacube.utils import geometry

filepath = '/g/data/r78/intertidal/GA_tidal_model.shp'

with fiona.open(filepath) as Input:                   
    crs = CRS(str(Input.crs_wkt))
    for feature in Input:
    if feature['properties']['ID'] == 18:
        geom=feature['geometry']
        boundary_polygon = Geometry(geom, crs)
        #print (feature)
        break

indexers={'time':('2013-06-23 00:00:00', '2013-06-29 23:59:59'), 'measurements':['red'],'geopolygon': boundary_polygon, 'group_by':'solar_day'}

datasets = dc.find_datasets(product='ls8_nbar_albers', **indexers)
group_by = query_group_by(group_by='solar_day')
sources = dc.group_datasets(datasets, group_by)
geobox = GeoBox.from_geopolygon(boundary_polygon, (-25, 25))

tl_ob=Tile(sources, geobox)
ds=GridWorkflow.load(tl_ob)

### Environment information

* Which ``datacube --version`` are you using?
1.3.2
* What datacube deployment/enviornment are you running against?
agdc-py3-prod

**Comment by andrewdhicks** [comment] 2017-06-05 01:28
This is caused by an error in rasterio, that has been fixed but not yet released. https://github.com/mapbox/rasterio/issues/1056

In the meantime, datacube-core v1.4.1 has a workaround, and is installed at NCI.
I can't access the shapefile to test it, so could you please test it against `agdc-py3-prod/1.4.1`, or put the shapefile somewhere in the u46 project folder?

I'm also looking into why the reprojection is happening, when it shouldn't need to.

**Comment by Bis-Bala** [comment] 2017-06-05 01:40
Yes it worked in latest agdc v1.4.1 module.
I copied and have permission set up for vector files /g/data/u46/users/bxb547/GA_tidal_model* .
You can read now.

**Comment by andrewdhicks** [comment] 2017-06-05 02:24
The reprojection is happening because we are comparing the source and requested CRS objects to see if they are equal, and they are being considered different, even though they are not.

To avoid the reprojection (and the inefficient workaround), try forcing the polygon CRS to be the same as the requested data:
`boundary_polygon = boundary_polygon.to_crs(CRS('EPSG:3577'))`

I'll raise a separate issue for the CRS equality check.

**Comment by andrewdhicks** [comment] 2017-06-07 05:01
This looks like it will be included in the `rasterio` release 1.0a9.
CRS issue raised as #243, so I'll close this issue.

**Closed as completed by andrewdhicks** 2017-06-07 05:01 UTC
