### ISSUE TITLE
Rasterio error in dc.load with rasterio==1.0a12 version

### ISSUE THREAD

**Issue by loicdtx** [opendatacube/datacube-core#421] opened 2018-04-17 23:43 UTC
When trying to load a chunk of an ingested collection with `dc.load()` I get the following error.

```python
import datacube

dc = datacube.Datacube()
sr = dc.load(product = 's2_l2a_20m_mexico',
             x = (-111.8, -111.4),
             y = (25, 25.4))
```
```bash
Error opening source dataset: NetCDF:/home/madmex_user/datacube_ingest/s2_l2a_20m/mexico/s2_l2a_20m_5_-10_20180102180250000000.nc:blue
Traceback (most recent call last):
  File "rasterio/_base.pyx", line 131, in rasterio._base.DatasetBase.__init__
  File "rasterio/_shim.pyx", line 64, in rasterio._shim.open_dataset
  File "rasterio/_err.pyx", line 188, in rasterio._err.exc_wrap_pointer
rasterio._err.CPLE_OpenFailedError: NetCDF:/home/madmex_user/datacube_ingest/s2_l2a_20m/mexico/s2_l2a_20m_5_-10_20180102180250000000.nc:blue: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "git/antares3-sandbox/scripts/sentinel_load_test.py", line 6, in <module>
    y = (25, 25.4))
  File "/home/madmex_user/.virtualenvs/antares/lib/python3.5/site-packages/datacube/api/core.py", line 327, in load
    fuse_func=fuse_func, dask_chunks=dask_chunks)
  File "/home/madmex_user/.virtualenvs/antares/lib/python3.5/site-packages/datacube/api/core.py", line 517, in load_data
    geobox, measurements, data_func)
  File "/home/madmex_user/.virtualenvs/antares/lib/python3.5/site-packages/datacube/api/core.py", line 450, in create_storage
    data = data_func(measurement)
  File "/home/madmex_user/.virtualenvs/antares/lib/python3.5/site-packages/datacube/api/core.py", line 507, in data_func
    fuse_func=fuse_func)
  File "/home/madmex_user/.virtualenvs/antares/lib/python3.5/site-packages/datacube/api/core.py", line 578, in _fuse_measurement
    skip_broken_datasets=skip_broken_datasets)
  File "/home/madmex_user/.virtualenvs/antares/lib/python3.5/site-packages/datacube/storage/storage.py", line 201, in reproject_and_fuse
    read_from_source(sources[0], destination, dst_transform, dst_nodata, dst_projection, resampling)
  File "/home/madmex_user/.virtualenvs/antares/lib/python3.5/site-packages/datacube/storage/storage.py", line 143, in read_from_source
    with source.open() as src:
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/home/madmex_user/.virtualenvs/antares/lib/python3.5/site-packages/datacube/storage/storage.py", line 422, in open
    raise e
  File "/home/madmex_user/.virtualenvs/antares/lib/python3.5/site-packages/datacube/storage/storage.py", line 389, in open
    with rasterio.open(self.filename) as src:
  File "/home/madmex_user/.virtualenvs/antares/lib/python3.5/site-packages/rasterio/__init__.py", line 240, in open
    s = DatasetReader(fp, driver=driver, **kwargs)
  File "rasterio/_base.pyx", line 133, in rasterio._base.DatasetBase.__init__
rasterio.errors.RasterioIOError: NetCDF:/home/madmex_user/datacube_ingest/s2_l2a_20m/mexico/s2_l2a_20m_5_-10_20180102180250000000.nc:blue: No such file or directory
```

Note that when using rasterio 0.36 (the stable version for now) everything works as expected. However, using the 1.0a12 has some benefits (e.g. much faster resampling), and is eventually become the stable version.

I'm using `datacube 1.6rc1` version, but I had noticed the same issue on previous versions.

**Comment by Kirill888** [comment] 2018-04-17 23:50
RasterIO is a wrapper around gdal, so your gdal needs to understand netcdf files, can you try this command

```
gdalinfo NetCDF:/home/madmex_user/datacube_ingest/s2_l2a_20m/mexico/s2_l2a_20m_5_-10_20180102180250000000.nc:blue
```

If this complains about no such file also then the problem is with gdal not with rasterio.

**Comment by loicdtx** [comment] 2018-04-17 23:58
The `gdalinfo` command works fine (I get all the metadata of that subdataset) and the `gdal-config --formats` list contains the netcdf driver.

**Comment by Kirill888** [comment] 2018-04-18 00:10
How about `rio info NetCDF:/home/madmex_user/datacube_ingest/s2_l2a_20m/mexico/s2_l2a_20m_5_-10_20180102180250000000.nc:blue`

I have tried that version of rio on my machine it seems to work

**Comment by Kirill888** [comment] 2018-04-18 00:17
Also our automation tests run against that version of rasterio without problems:

https://travis-ci.org/opendatacube/datacube-core/jobs/367559424#L1259

**Comment by loicdtx** [comment] 2018-04-18 01:48
The `rio info` commands  (or opening a dataset from the interpreter with `rasterio.open`) work if I install `rasterio` directly from the repos (`pip install git+https://github.com/mapbox/rasterio.git`). But none of it work with the pypi version.

**Comment by Kirill888** [comment] 2018-04-18 01:54
pypi version might be pre-compiled against some incompatible gdal? Maybe if you force non-binary install from pypi it will work also.

**Comment by Kirill888** [comment] 2018-04-18 01:56
I would suggest installing a specific release though

```
pip install git+https://github.com/mapbox/rasterio.git@1.0a12
```

**Comment by loicdtx** [comment] 2018-04-18 02:03
Nice catch! Installing with `pip install rasterio==1.0a12 --no-binary rasterio` solved the issue

**Comment by Kirill888** [comment] 2018-04-18 02:05
Good, closing this

**Closed as completed by Kirill888** 2018-04-18 02:05 UTC
