### ISSUE TITLE
Carry resolution information when loading

### ISSUE THREAD

**Issue by emmaai** [opendatacube/datacube-core#769] opened 2019-07-18 09:03 UTC
### Expected behaviour
Should be able to get the resolution  from `xarray.attrs` when the `xarray.shape=(1, 1)`

### Actual behaviour
`xarray.geobox` fails without any error message

Related #752

**Comment by uchchwhash** [comment] 2019-07-18 11:42
Essentially duplicate of #752, I think we should continue the discussion there.

**Closed as completed by uchchwhash** 2019-07-18 11:42 UTC
