### ISSUE TITLE
Test cases not passing

### ISSUE THREAD

**Issue by sathwikreddy56** [opendatacube/datacube-core#1386] opened 2023-01-21 18:52 UTC
Tests from 
test_geometry.py
test_grid_workflow.py
test_virtual.py are failing.py

even after installing all the libraries properly some throw error from
test_common.py
test_dataset_add.py
test_util_docs.py 

### Actual behaviour
ERROR tests/test_utils_docs.py::test_read_docs_from_http
ERROR tests/ui/test_common.py::test_ui_path_doc_stream
ERROR integration_tests/test_dataset_add.py::test_dataset_add_http[US/Pacific-datacube]
ERROR integration_tests/test_dataset_add.py::test_dataset_add_http[UTC-datacube]
FAILED tests/test_geometry.py::test_ops - AttributeError: 'LineString' object has no attribute '__array_interface__'
FAILED tests/test_geometry.py::test_geom_split - TypeError: 'GeometryCollection' object is not iterable
FAILED tests/test_geometry.py::test_chop - TypeError: 'GeometryCollection' object is not iterable
FAILED tests/test_geometry.py::test_wrap_dateline - TypeError: 'GeometryCollection' object is not iterable
FAILED tests/test_geometry.py::test_wrap_dateline_sinusoidal[pts0] - TypeError: 'GeometryCollection' object is not iterable
FAILED tests/test_geometry.py::test_wrap_dateline_sinusoidal[pts1] - TypeError: 'GeometryCollection' object is not iterable
FAILED tests/test_geometry.py::test_wrap_dateline_sinusoidal[pts2] - TypeError: 'GeometryCollection' object is not iterable
FAILED tests/test_geometry.py::test_wrap_dateline_utm - TypeError: 'GeometryCollection' object is not iterable
FAILED tests/test_geometry.py::test_geom_clone - assert <POLYGON ((0 0, 0 20, 10 20, 10 0, 0 0))> is not <POLYGON ((0 0, 0 20, 10 20, 10 0, 0 0))>
FAILED tests/api/test_grid_workflow.py::test_gridworkflow_with_time_depth - AssertionError
FAILED tests/api/test_virtual.py::test_aggregate - ValueError: time already exists as coordinate or variable name.
FAILED integration_tests/test_end_to_end.py::test_end_to_end[US/Pacific-datacube] - AssertionError
FAILED integration_tests/test_end_to_end.py::test_end_to_end[UTC-datacube] - AssertionError

... eg. Incorrect result, python stacktrace, etc. ...

### Steps to reproduce the behaviour

... Include code, command line parameters as appropriate ...

### Environment information

* Which ``datacube --version`` are you using?
* What datacube deployment/enviornment are you running against?

> **Note:** Stale issues will be automatically closed after a period of six months with no activity. 
> To ensure critical issues are not closed, tag them with the Github `pinned` tag.
> If you are a community member and not a maintainer please escalate this issue to maintainers via
> [GIS StackExchange](https://gis.stackexchange.com/questions/tagged/open-data-cube) or [Slack](http://slack.opendatacube.org).

**Comment by SpacemanPaul** [comment] 2023-01-22 22:26
Possibly a duplicate of #1334

**Comment by Ariana-B** [comment] 2023-01-24 01:12
Pinning the shapely version to be `< 2.0.0` should resolve the `LineString` and `GeometryCollection` related errors, which might in turn resolve the rest.

**Comment by Ariana-B** [comment] 2023-02-01 00:09
Shapely compatibility update in the latest release should resolve this.

**Closed as completed by Ariana-B** 2023-02-01 00:09 UTC
