### ISSUE TITLE
Query search fails when time range is 'None'

### ISSUE THREAD

**Issue by santoshamohan** [opendatacube/datacube-core#468] opened 2018-05-30 07:09 UTC
### Expected behaviour
When time range is 'None', query anything that need processing.

### Actual behaviour
Query is not successful when time range is 'None' (if we want to query products by time range).

### Steps to reproduce the behaviour
Include the following test code in the test_query.py and run a pytest on test_query.py file.

    query = Query(index=mock_index, time=None)
    assert 'time' not in query.search

### Environment information
Open Data Cube core, version 1.6rc1+28.ga69dfff

Module files used:
  1) pbs                2) git/2.9.5          3) dea-env/20180405   4) udunits/2.1.24     5) dea/20180515

**Comment by omad** [comment] 2018-08-29 10:54
I think this is a duplicate of #183 
Would definitely be useful though...

**Closed as completed by omad** 2018-08-29 10:54 UTC
