### ISSUE TITLE
Large data reads from S3 break the service and require FSx cache

### ISSUE THREAD

**Issue by whatnick** [opendatacube/datacube-core#1155] opened 2021-07-15 04:05 UTC
### Expected behaviour
Large concurrent data read from S3 work seamlessly

### Actual behaviour
Large concurrent reads particularly via Dask break the S3 API and cause read failures and processes hanging.

### Steps to reproduce the behaviour
See experiments by @emmaai .
Large Data Read:
![s3_read_breakage](https://user-images.githubusercontent.com/491396/125727207-b4d40fdb-22e0-49c2-8609-05df5ee5766c.png)

S3 Breakage:
![s3_5xx_errors](https://user-images.githubusercontent.com/491396/125727212-81c597e6-6a03-47e3-a77b-2080c5523bd1.png)

### Environment information

* Which ``datacube --version`` are you using? master
* What datacube deployment/enviornment are you running against? DEA Development Sandbox

### Proposed solution
Layer an FSx on S3

**Comment by emmaai** [comment] 2021-07-15 07:42
tag @JM-GA for this

**Comment by whatnick** [comment] 2021-07-16 01:13
Datacube can support multiple dataset locations per dataset. @benjimin  to confirm.

**Comment by woodcockr** [comment] 2022-03-10 21:35
This issue is pinned so presumably is an ongoing one. Unfortunately there is no information in regards to how reproduce the problem or what it actually is. based on the graphs alone I'm now seeing this issue at scales seemingly larger than those indicated. I can't help though without more information.
More information please or let the issue go stale.

**Comment by Kirill888** [comment] 2022-03-11 00:56
If I remember right that was caused by some misconfiguration during stats run, where chunk size was configured to be too small and maybe also there were too many threads per physical node as well and so it was kinda DDOSing S3 endpoint. I'm not sure what action can be taken on this issue, I suggest we close it.

**Comment by woodcockr** [comment] 2022-03-14 23:52
Agreed. Folks will be notified and can bring it back if need be.

**Closed as completed by woodcockr** 2022-03-14 23:52 UTC
Labels: enhancement, help wanted, discussion, pinned
