### ISSUE TITLE
Storage unit layer alias to enable lookup of common bands between sensors

### ISSUE THREAD

**Issue by simonaoliver** [opendatacube/datacube-core#62] opened 2016-01-07 02:35 UTC
Include band alias in the storage unit config/write to enable identification of specific bands between different sensors? eg. TM band 1, blue, 0.45-0.52 (wavelength interval) OLI band 2, blue, 0.45 - 0.51 (wavelength interval). Included in the dataset configuration.

**Comment by omad** [comment] 2016-01-07 02:38
I'm thinking that this type of variable specific information should be defined in the Storage Configuration files, which will then be searchable in the index, and should be written into the Storage Units too.

I need to check that this is all working as intended.

**Comment by mpaget** [comment] 2016-01-08 05:13
In the v2 design process we pushed layer aliases out to a “Semantics API” as one place for domain+AGDC-specific lookups. This semantics API could conceivably use vocabulary and other name look up services too.

I have no problem adding this type of info to the Storage Configuration files for now. Just be aware that there is an option for a more general approach.

I don’t agree that aliases should be written the Storage Units per se – from a design perspective, that is. Rather, Storage Units should not be relied on to hold metadata.

In the netCDF/HDF specific case, however, it makes sense to add CF compliant metadata. The CF-way for layer aliases is to use the “standard_name” attribute. Little point in adding our own “custom aliases”, I feel, as the goal of netcdf-cf is interoperability (outside of the agdc). If you get stuck with standard_names then I can help as I have some experience with them.

**Comment by omad** [comment] 2016-01-08 08:01
##### Semantics API

Is there any documentation about the Semantics API that I'm missing? I can't find it mentioned on the Data Cube Wiki.

##### Storage Unit Metadata

Querying and operation won't rely on metadata in the Storage Units. However, at least some Storage Units are going to be published through THREDDS and will contain comprehensive metadata.

##### CF `standard_name`

I'm very interested in talking to you about this @mpaget. The CF usage of `standard_name` seems too restrictive to include extended band metadata such as 'TM band 1, blue, 0.45-0.52 (wavelength interval)', it can only specify `bidirectional_surface_reflectance`, and further detail has to go as unstructured text in `long_name`.

**Comment by mpaget** [comment] 2016-01-10 23:05
Semantics API
Comes from v2 workshops. Documentation is likely not complete but there’s likely a mention of it somewhere - will be revisited in the current round (Jan 2016) of reworking the v2 documentation. Continue with including semantics in the yaml defs for now – which will help identify the problem space – and we can switch over to something like a semantics API if agreeable to all. Alex Ip and/or Leo had some good awareness of the semantics problem so it might be worth talking to them too. The trick is that it’s a many to one mapping from a user’s language/discipline/point-of-view to the labels used in the Index and Units, so for genericity, we thought it easier/more-extensible to park the semantics mapping closer to the user than to the Index and Units.
Storage Unit Metadata
Good.
CF standard_name
Agreed. The standard_name attribute is not well suited to generic/semantic mappings but it is the attribute that provides for standardised or common names, which is as close as CF comes to some sort of creator-independent labelling. CF is about interoperability between publicly accessible data files, whereas semantics in the AGDC is about mapping from users’ language to the labels used in the Index and Units.

**Comment by v0lat1le** [comment] 2016-01-10 23:16
I suggest we store band metadata (like wavelength interval, spectral sensitivity, etc..) in the storage unit metadata (following CF, ACDD or other conventions where relevant), as well as in the datacube database.

This way consumers of the data have the power to decide on how to combine the data coming off different sensors.

Datacube API could provide algorithms for most common uses cases (once those are identified).

**Comment by woodcockr** [comment] 2016-01-10 23:35
That's consistent with the v2 design goals (including the algorithms for the most common use-cases). Happy new year to you all as well, I just got back and am catching up with the work done.

**Comment by cet900** [comment] 2016-01-11 23:00
Just backing up @mpaget 's comment that `standard_name` is a restrictive vocabulary that enables interoperability, it's not a full semantic mapping. The extended attributes like wavelength, colour, band number, etc., need to go in other variable metadata fields - could be `long_name`, but you can also define any other fields you want, CF is the minimum requirement, so as well as `variable.standard_name`, `variable.long_name` and `variable.units` you can totally also define `variable.central_wavelength`, `variable.bandwidth`, and anything else that might be required for internal self-description of the data in the file. Contact [Kelsey](mailto:Kelsey.Druken@anu.edu.au) if you want to check the current compliance status of the files or ask what other groups are doing. :)

**Comment by v0lat1le** [comment] 2016-04-22 05:01
I believe this is being addressed by #93

**Closed as completed by v0lat1le** 2016-04-22 05:01 UTC
Labels: question
