### ISSUE TITLE
Error in ingesting Landsat data in UTM when resolution is 30 m

### ISSUE THREAD

**Issue by davidedelerma** [opendatacube/datacube-core#313] opened 2017-10-16 12:34 UTC
### Expected behaviour
I should be able to ingest successfully Landsat L2 data in UTM projection using 30 m as cell size.

### Actual behaviour
When try to ingest Landsat data in UTM projection using 30 m resolution, I get the error:
```bash
"""
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/ubuntu/Datacube/agdc-v2/datacube/executor.py", line 151, in _run_cloud_pickled_function
    return func(*args, **kwargs)
  File "/home/ubuntu/Datacube/agdc-v2/datacube/scripts/ingest.py", line 219, in ingest_work
    data = Datacube.load_data(tile.sources, tile.geobox, measurements, fuse_func=fuse_func)
  File "/home/ubuntu/Datacube/agdc-v2/datacube/api/core.py", line 491, in load_data
    geobox, measurements, data_func)
  File "/home/ubuntu/Datacube/agdc-v2/datacube/api/core.py", line 428, in create_storage
    data = data_func(measurement)
  File "/home/ubuntu/Datacube/agdc-v2/datacube/api/core.py", line 484, in data_func
    skip_broken_datasets=skip_broken_datasets)
  File "/home/ubuntu/Datacube/agdc-v2/datacube/api/core.py", line 550, in _fuse_measurement
    skip_broken_datasets=skip_broken_datasets)
  File "/home/ubuntu/Datacube/agdc-v2/datacube/storage/storage.py", line 195, in reproject_and_fuse
    read_from_source(sources[0], destination, dst_transform, dst_nodata, dst_projection, resampling)
  File "/home/ubuntu/Datacube/agdc-v2/datacube/storage/storage.py", line 153, in read_from_source
    numpy.copyto(dest, tmp, where=(tmp != src.nodata))
TypeError: Cannot cast scalar from dtype('int16') to dtype('uint8') according to the rule 'same_kind'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/Datacube/agdc-v2/datacube/scripts/ingest.py", line 273, in process_tasks
    executor.result(future)
  File "/home/ubuntu/Datacube/agdc-v2/datacube/executor.py", line 219, in result
    return future.result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
TypeError: Cannot cast scalar from dtype('int16') to dtype('uint8') according to the rule 'same_kind'
0 successful, 60 failed
```
The data can be successfully ingested for others resolutions (e.g. 20 m or 30.1 m).
`tile_size` is obtained with: `resolution` * 3500

### Steps to reproduce the behaviour
- run `datacube -v product add ~/Datacube/agdc-v2/ingest/dataset_types/landsat_collection/ls7_collections_sr_italy.yaml`
- run `datacube -v dataset add /datacube/original_data/USGS/Landsat7/Italy/LE071900312002100201T1-SC20171013101528/datacube-metadata.yaml`
- run `datacube -v ingest -c ~/Datacube/agdc-v2/ingest/ingestion_configs/landsat_collection/ls7_collections_sr_italy.yaml --executor multiproc 2`

The parameters used in the ingestion configuration file for the tiles are:

```yaml
storage:
  driver: NetCDF CF

  crs: EPSG:32633
  tile_size:
          x: 105000.0
          y: 105000.0
  resolution:
          x: 30.0
          y: -30.0
  chunking:
      x: 200
      y: 200
      time: 1
  dimension_order: ['time', 'y', 'x']
```

This has been tested with multiple datasets, so it should be reproducible with any Landsat L2 Dataset

### Environment information

Datacube version: 
Open Data Cube core, version 1.1.15+615.gd348e71.dirty

**Comment by bellemae** [comment] 2017-10-16 23:56
Hi @davidedelerma, 

USGS L2 landsat data ingestion isn't currently supported in Open Data Cube. 
However, I notice that you're using a fairly old version of ODC (1.1.15), it may be worth updating to the latest version (1.5.2) and trying the ingestion with that.

**Comment by bellemae** [comment] 2017-10-17 01:18
@davidedelerma

The data type error you're getting could be related to an incompatible nodata value. 
What is the data type for your data? If it's uint8, then your nodata value can't be -999

**Comment by davidedelerma** [comment] 2017-10-17 15:41
Hi @bellemae  
Thanks for the reply.   
I tried with the version 1.5.2 of Datacube, but I still get the same problem.
However, modifying the atmos_opacity parameter in the product configuration file from:
```yaml
     - name: 'sr_atmos_opacity'
      aliases: [atmos_op]
      dtype: uint8
      nodata: 0
      units: 'unitless'
```
to:
```yaml
    - name: 'sr_atmos_opacity'
      aliases: [atmos_op]
      dtype: int16
      nodata: -9999
      units: 'unitless'
```
and the same parameter in the ingestion configuration file from:
```yaml
    - name: 'atmos_opacity'
      dtype: uint8
      nodata: 0
      resampling_method: nearest
      src_varname: 'sr_atmos_opacity'
      zlib: True
      attrs:
          long_name: "Atmospheric Opacity"
          alias: [sr_atmos_opacity]
```
to
```yaml
    - name: 'atmos_opacity'
      dtype: int16
      nodata: -9999
      resampling_method: nearest
      src_varname: 'sr_atmos_opacity'
      zlib: True
      attrs:
          long_name: "Atmospheric Opacity"
          alias: [sr_atmos_opacity]
```
I can ingest the data successfully using 30 meters resolution, but we noticed that the difference between the ingested data and indexed data is not 0.
The data were ingested using the appropriate projection (in our case EPSG:32636) and 30 m resolution.  
The code we used to make the comparison is: 
```python
import datacube
import numpy as np
dc = datacube.Datacube()
output_crs = 'EPSG:32636'
x_resolution = 30
y_resolution = 30
data_indexed = dc.load(product='ls7_collections_sr_scene',
                       output_crs = output_crs,
                       resolution = (-y_resolution, x_resolution),
                       resampling=None)
data_ingested = dc.load(product = 'ls7_ledaps_karamoja',
                        platform = 'LANDSAT_7',
                        output_crs = output_crs,
                        resolution = (-y_resolution, x_resolution))
indexed = data_indexed.sr_band1.values[0]
ingested = data_ingested.blue.values[0]
diff = indexed - ingested
print("Data type of the difference:", diff.dtype)
print(np.iinfo(diff.dtype))
print()
print("Difference min value:", diff.min())
print("Difference max value:", diff.max())
print()
print("Indexed data:")
print("Data type:", indexed.dtype)
print("Indexed min value:", indexed.min())
print("Indexed max value:", indexed.max())
print()
print("Ingested data:")
print("Data type:",ingested.dtype)
print("Ingested min value:", ingested.min())
print("Ingested max value:", ingested.max())
```
The result obtained for this dataset is:

Data type of the difference: int16  
Machine parameters for int16  
min = -32768  
max = 32767  

Difference min value: -18833  
Difference max value: 18610  

Indexed data:  
Data type: int16  
Indexed min value: -9999  
Indexed max value: 20000  

Ingested data:  
Data type: int16  
Ingested min value: -9999  
Ingested max value: 20000  

We tried also with L1 data but we got the same kind of problem.  
We noticed also that the difference between ingested and indexed data is 0 when we set the resolution to a value different from 30 (e.g. 30.1).

**Comment by bellemae** [comment] 2017-10-17 23:26
Great to see you got it a little further :)
As for the differences you're getting, plotting them to see where they're occurring may help determine the cause. Could you please post a plot of the differences?

**Comment by davidedelerma** [comment] 2017-10-20 09:21
Hi @bellamie,  
Thanks :)
Here are two plots showing the difference between ingested data and indexed data for the bands blue and pixel qa respectively.  
The points for which the difference is 0 have been masked to enhance the points for which the difference is not 0.  
![diff_blue_and_pixelqa](https://user-images.githubusercontent.com/15250055/31813582-3b35f834-b587-11e7-8c0a-541b5d1b22c9.png)
Here below is another example showing the difference between ingested and indexed data.  
The image is obtained taking the RGBs for indexed and ingested data, changing the colour scale to grey scale and subtract them
![diff_greyscale_1](https://user-images.githubusercontent.com/15250055/31814752-e0428646-b58a-11e7-8528-86eed73b85d9.png)

**Comment by andrewdhicks** [comment] 2017-10-23 07:07
Hi @davidedelerma 

In your previous code snippet, you were ingesting into CRS `EPSG:32633`. There will be resampling artifacts from the 2 sets or `nearest neighbor` re-projections.
If you are only doing one reprojection, then I'm not sure what could be happening, as the "on-the-fly" reprojection should be the same method that creates the "ingested" tiled version.

Andreia also passed along your question on the 25m resolution in Digital Earth Australia products.
While USGS publishes in 30m, the actual sensor pixel size is closer to ~27.5m, depending on variations of the ground and platform.  Australia decided to use 25m to make a nested grid compatible with a suite of other products (eg MODIS) with standard resolutions (eg. 50m, 250m, 500m,...) 
http://www.anzlic.gov.au/resources/national-nested-grid

**Comment by davidedelerma** [comment] 2017-10-23 13:34
Hi @andrewdhicks,
Thanks for your answer.
We tested the Open Data Cube with two different Landsat 7 datasets, one from Italy with crs: 32633 and one from Uganda with crs: 32636, for this reason the crs in the previous posts were different for indexed and ingested data.
We double checked and the indexed and ingested data for the same dataset have the same projection, for this reason it looks odd to have this difference between the indexed and ingested data.
The interpolation method used for ingestion and loading was nearest neighbour.
We noticed, though, that when we ingest and load the data using cubic spline method, as interpolation method, the difference between ingested and indexed data is 0.
Then we made some further testing and we noticed that when we load the data using 60 m cell size and cubic spline interpolation the two grids are again different. We didn't expect such a difference as we started from the same initial conditions.

Thanks,
Davide

**Comment by Kirill888** [comment] 2017-10-25 05:44
Hi Davide @davidedelerma 

I think differences you are observing stem from the resampling ingestion process performs. Even though you are ingesting in to the same CRS at the same scale there is still resampling that needs to be applied. Ingestor needs to align pixel boundaries, so it will perform sub-pixel translation even if you match crs and scale exactly, for that reason I would recommend against using `nearest neighbour` for ingestion as this would introduce artefacts when performing sub-pixel translation.

Try this:
ingestion-time: use cubic interpolation
load time for scene: use cubic interpolation
load time for ingested data: use nearest neighbour

With this you should get data that is much more similar or ideally the same.

Also ingestion process is not a requirement, if you are not performing re-projection or scale change you can just as well query your original data without incurring significant processing penalty, no need to ingest.

**Comment by davidedelerma** [comment] 2017-10-26 05:44
Hi @Kirill888 ,
Thank you very much, I tried the suggested test and the difference between ingested and indexed data is 0.
Now the ingestion process is more clear.
Thanks

**Comment by Kirill888** [comment] 2017-10-26 05:48
No worries.

I'm closing this issue then.

**Closed as completed by Kirill888** 2017-10-26 05:48 UTC
