### ISSUE TITLE
Datacube load_data() only returning first layer from multi-layer GeoTIFF

### ISSUE THREAD

**Issue by roarmstrong** [opendatacube/datacube-core#457] opened 2018-05-22 05:52 UTC
Potentially relates to #396 

When using `load_data()` on datasets backed by a single layered GeoTIFF datacube is only returning the data from a single layer regardless of which layer is requested.

This appears to occur when datacube uses a `BandDataSource` instead of an `OverrideBandDataSource` for bands > 1.

A small notebook demonstrates the difference here: https://gist.github.com/roarmstrong/18ee7ef4f1e194a9f9ca5677a4e41b68

The code for reprojecting a `BandDataSource` may need to be modified or the logic https://github.com/opendatacube/datacube-core/blob/ee33766c557a6c4428b065277a5760dac78e2ac0/datacube/storage/storage.py#L418-L428 may need to be reconsidered.

**Comment by Kirill888** [comment] 2018-05-22 06:00
@roarmstrong Can you please supply version of rasterio and gdal you have installed

**Comment by roarmstrong** [comment] 2018-05-22 06:02
Running:
`rasterio==1.0a12`
`gdal==2.2.4`

**Comment by Kirill888** [comment] 2018-05-22 06:58
Problem seems to be with rasterio, submitted issue here:

https://github.com/mapbox/rasterio/issues/1350

see this gist:

https://gist.github.com/Kirill888/4021efe5b2a9c4de1946116eb31af3d4

**Comment by Kirill888** [comment] 2018-05-22 22:53
error in rasterio confirmed on their side, suggested work around is to warp the whole src image in one go which works, but doesn't fit our model.

More concerning is that stacked netcdfs are most likely also affected, so current NCI install needs to be checked, we don't often read with warping from ingested products, and looks like we are not testing this case either which is the worst combination.

**Comment by Kirill888** [comment] 2018-05-23 01:11
Loads from netcdf on NCI aren't affected by this luckily

https://gist.github.com/Kirill888/edb21175e351ae2fe30637c1c9ccd6d1

**Comment by omad** [comment] 2018-05-30 10:06
Also luckily, on the NCI, all of the Landsat scene products we read from are single band GeoTIFFs.

**Comment by Kirill888** [comment] 2018-08-06 00:45
This was rasterio problem fixed in 1.0.2 release of rasterio.

**Closed as completed** 2018-08-06 00:45 UTC
Labels: bug, loading data
