### ISSUE TITLE
Command " datacube -v system init " giving error with click.py

### ISSUE THREAD

**Issue by ghost** [opendatacube/datacube-core#645] opened 2019-02-06 16:04 UTC
### Expected behaviour
As per the https://datacube-core.readthedocs.io/en/latest/ops/db_setup.html#create-configuration-file

### Actual behaviour

[root@eordbtest datacube]# datacube -v system init
/root/miniconda3/lib/python3.7/site-packages/psycopg2-2.7.7-py3.7-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
2019-02-06 16:03:10,363 26931 datacube INFO Running datacube command: /root/miniconda3/bin/datacube -v system init
Traceback (most recent call last):
  File "/root/miniconda3/bin/datacube", line 11, in <module>
    load_entry_point('datacube==1.6.2+348.gca72ac5.dirty', 'console_scripts', 'datacube')()
  File "/root/miniconda3/lib/python3.7/site-packages/Click-7.0-py3.7.egg/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/root/miniconda3/lib/python3.7/site-packages/Click-7.0-py3.7.egg/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/root/miniconda3/lib/python3.7/site-packages/Click-7.0-py3.7.egg/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/miniconda3/lib/python3.7/site-packages/Click-7.0-py3.7.egg/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/miniconda3/lib/python3.7/site-packages/Click-7.0-py3.7.egg/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/miniconda3/lib/python3.7/site-packages/Click-7.0-py3.7.egg/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/root/miniconda3/lib/python3.7/site-packages/datacube-1.6.2+348.gca72ac5.dirty-py3.7.egg/datacube/ui/click.py", line 186, in new_func
    parsed_config = config.LocalConfig.find(paths=paths, env=specific_environment)
AttributeError: type object 'LocalConfig' has no attribute 'find'

### Steps to reproduce the behaviour

Run command " datacube -v system init " after Normal git repo installed on Centos and changed config file to the available one here https://datacube-core.readthedocs.io/en/latest/_modules/datacube/config.html

### Environment information

Click 7
Datacube 1.6.2
GDAL 2.4

**Comment by JackLidge** [comment] 2019-02-07 14:32
I performed a fresh datacube install on Centos 6.9 a couple of days ago and it didn't work fully until I upgraded all packages in conda and then downgraded to GDAL 2.3.3. Ran a successful datacube system init after that.

**Comment by ghost** [comment] 2019-02-07 15:17
Thanks for your reply. I also get the error "No ODC environment, checked configurations for ['default', 'datacube']" after I reinstall again everything. Any ideas how to solve this. Thanks

**Comment by JackLidge** [comment] 2019-02-07 17:50
could be either that you don't have the virtual environment activated (have you run source activate cubeenv before doing that?) or your config file isn't set up/is set up weirdly. Check at ~/.datacube.conf and check that you've got it set up as required here: https://datacube-core.readthedocs.io/en/latest/ops/db_setup.html (under "create configuration file").

**Comment by ghost** [comment] 2019-02-08 10:16
I changed the config file as per you suggested and on the page https://datacube-core.readthedocs.io/en/latest/ops/db_setup.html , but I get below error in config.py file,

db_hostname: localhost
              ^
SyntaxError: invalid syntax

Can you please send me the working config.py file ? Below see a section of my current config.py file thats generating the error, maybe you can help solve it,

"""
User configuration.
"""

import os

ENVIRONMENT_VARNAME = 'DATACUBE_CONFIG_PATH'
#: Config locations in order. Properties found in latter locations override
#: earlier ones.
#:
#: - `/etc/datacube.conf`
#: - file at `$DATACUBE_CONFIG_PATH` environment variable
#: - `~/.datacube.conf`
#: - `datacube.conf`
DEFAULT_CONF_PATHS = (
    '/etc/datacube.conf',
    os.environ.get(ENVIRONMENT_VARNAME),
    os.path.expanduser("~/.datacube.conf"),
    'datacube.conf'
)

DEFAULT_ENV = 'default'

_DEFAULT_CONF = (
[DEFAULT]
db_hostname: localhost
db_database: datacube
index_driver: default

db_connection_timeout: 60

[user]
default_environment: datacube
)
_UNSET = object()

def read_config(default_text=None):
    import configparser
    config = configparser.ConfigParser()
    if default_text:
        config.read_string(default_text)
    return config


class LocalConfig(object):
    """
    System configuration for the user.

    This loads from a set of possible configuration files which define the available environments.
    An environment contains connection details for a Data Cube Index, which provides access to
    available data.

    """

**Comment by JackLidge** [comment] 2019-02-08 10:34
I think you don't want to be playing around with the config.py file  - I've just checked mine and the _DEFAULT_CONF section is as follows:

```_DEFAULT_CONF = u"""
[DEFAULT]
# Blank implies localhost
db_hostname:
db_database: datacube
index_driver: default
# If a connection is unused for this length of time, expect it to be invalidated.
db_connection_timeout: 60

[user]
# Which environment to use when none is specified explicitly.
#   note: will fail if default_environment points to non-existent section
# default_environment: datacube
"""
```

What I've always done when setting up a datacube is to set up a file called ~/.datacube.conf, which I then write the config settings as suggested by the docs in. For example, my current .datacube.conf file is:

```
[datacube]
db_database: datacube

# A blank host will use a local socket. Specify a hostname (such as localhost) to use TCP.
db_hostname: localhost

# Credentials are optional: you might have other Postgres authentication configured.
# The default username otherwise is the current user id.
db_username: postgres
db_password: [my password]
```

Check using gedit or another text editor at ~/.datacube.conf to ensure you've got this configuration file set up as I believe you won't be able to access the datacubes database without it.

**Comment by ghost** [comment] 2019-02-08 12:40
Yea playing around with the config.py file was not a good idea.

**Comment by Kirill888** [comment] 2019-03-25 22:53
look like a duplicate of #517

**Closed as completed by Kirill888** 2019-03-25 22:53 UTC

**Comment by ghost** [comment] 2020-04-15 13:19
I have downloaded the package into the root directory so when I run this command : datacube system check 
it shows me this output : 
Version:       1.7+0.g98cf9ba3.dirty
Config files:  /root/.datacube.conf
Host:          127.0.0.1:5432
Database:      datacube
User:          dc_user
Environment:   None
Index Driver:  default

so is it fine to go on ? and in the ~/Datacube/data_cube_ui/config/dc_ui.conf is it ok to leave the address to /home/localuser/datacube ? or do I have to change it ? to root/datacube ?
